name: Build Dev

on:
  push:
    branches:
      - dev
      - master

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # 复制环境变量文件
      - name: Copy .env.example
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          else
            echo ".env file already exists. Skipping the copy step."
          fi

      # 安装项目依赖
      - name: Install Dependencies
        run: npm install

      # 构建程序
      - name: Build Website
        run: npm run build
        # 默认的 GITHUB_TOKEN 会自动传递，无需显式传递

      # 查看构建后的目录
      - name: List build directory
        run: ls -alh dist  # 确保 dist 是正确的构建目录

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 或者使用 ACCESS_TOKEN
